services:
  - docker
language: minimal
before_install:
- docker pull gin078/aur-bldr
- env | grep "AUR" > .env
- docker run -it gin078/aur-bldr sudo pacman -Syyu --noconfirm --noprogress

script:
- docker run -it --env-file .env gin078/aur-bldr

env:
- AUR_PACKAGE=python2-bitcoinrpc-git
- AUR_PACKAGE=python-matplotlib-venn
- AUR_PACKAGE=python2-pysha3
- AUR_PACKAGE=python2-markdown2-git
- AUR_PACKAGE=python35
- AUR_PACKAGE=grafana-git
- AUR_PACKAGE=mypy-git
- AUR_PACKAGE=ptpd
- AUR_PACKAGE=chronograf
- AUR_PACKAGE=fzf-git
- AUR_PACKAGE=wxtoimg
- AUR_PACKAGE=aisdeco2
- AUR_PACKAGE=bitbake
- AUR_PACKAGE=zsh-pure-prompt-git
- AUR_PACKAGE=snap-telemetry
- AUR_PACKAGE=ptpd-git
- AUR_PACKAGE=python-influxdb-git
- AUR_PACKAGE=chronograf-bin
- AUR_PACKAGE=proxysql
- AUR_PACKAGE=etcher-cli-bin
- AUR_PACKAGE=python2-docker-py-git
- AUR_PACKAGE=python-balena
- AUR_PACKAGE=balena-etcher
- AUR_PACKAGE=ci-node-modules
- AUR_PACKAGE=balena-deploy-request
- AUR_PACKAGE=ply-git
