services:
  - docker
language: shell
os: linux
before_install:
- env | grep "AUR" > .env
script:
- docker run --rm --env-file .env gin078/aur-bldr

stages:
  - name: check package versions
    if: branch = versions
  - name: rebuild docker image
    if: type = cron
  - name: test
    if: branch = master

jobs:
  allow_failures:
    - env: AUR_PACKAGE=bitbake AUR_PACKAGE=proxysql
  include:
    - stage: recheck package versions
      script:
      - update_versions.sh
    - stage: rebuild docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t aur-bldr .
      - docker images
      - docker tag aur-bldr $DOCKER_USERNAME/aur-bldr
      - docker push $DOCKER_USERNAME/aur-bldr
    - stage: test
      git:
        clone: false

      env:
      - AUR_PACKAGE=aisdeco2
      - AUR_PACKAGE=balena-cli
      - AUR_PACKAGE=balena-deploy-request
      - AUR_PACKAGE=balena-engine
      - AUR_PACKAGE=balena-etcher
      - AUR_PACKAGE=bitbake
      - AUR_PACKAGE=chronograf
      - AUR_PACKAGE=chronograf-bin
      - AUR_PACKAGE=ci-node-modules
      - AUR_PACKAGE=electron7-bin
      - AUR_PACKAGE=etcher-cli-bin
      - AUR_PACKAGE=fzf-git
      - AUR_PACKAGE=geeknote-improved-git
      - AUR_PACKAGE=grafana-git
      - AUR_PACKAGE=mypy-git
      - AUR_PACKAGE=ply-git
      - AUR_PACKAGE=proxysql
      - AUR_PACKAGE=ptpd
      - AUR_PACKAGE=ptpd-git
      - AUR_PACKAGE=python2-bitcoinrpc-git
      - AUR_PACKAGE=python2-docker-pycreds
      - AUR_PACKAGE=python2-docker-py-git
      - AUR_PACKAGE=python2-markdown2-git
      - AUR_PACKAGE=python2-pysha3
      - AUR_PACKAGE=python35
      - AUR_PACKAGE=python-balena
      - AUR_PACKAGE=python-influxdb-git
      - AUR_PACKAGE=python-matplotlib-venn
      - AUR_PACKAGE=snap-telemetry
      - AUR_PACKAGE=versionist
      - AUR_PACKAGE=wxtoimg
      - AUR_PACKAGE=yq2-bin
      - AUR_PACKAGE=zsh-pure-prompt
      - AUR_PACKAGE=zsh-pure-prompt-git
