#!/bin/bash

pkgs=$(AUR_MAINTAINER=gin078 python aur-search.py)
cat travis.base.yml > .travis.yml
cat travis.comaintainers.yml >> .travis.yml
echo "${pkgs}" | grep -v bitbake >> .travis.yml

git add .travis.yml
