services:
  - docker
language: minimal
before_install:
- env | grep "AUR" > .env
script:
- docker run --rm --env-file .env gin078/aur-bldr

jobs:
  include:
      #- stage: rebuild docker image
      #  script:
      #  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      #  - docker build -t aur-bldr .
      #  - docker images
      #  - docker tag gin078/aur-bldr $DOCKER_USERNAME/aur-bldr
      #  - docker push $DOCKER_USERNAME/aur-bldr
    - stage: test
      allow_failures:
        - env: AUR_PACKAGE=bitbake
      git:
        clone: false

env:
