services:
  - docker
language: shell
os: linux
before_install:
- env | grep "AUR" > .env
script:
- docker run --rm --env-file .env gin078/aur-bldr

stages:
  - name: check package versions
    if: branch = versions
  - name: rebuild docker image
    if: type = cron
  - name: test
    if: branch = master

jobs:
  allow_failures:
    - env: AUR_PACKAGE=bitbake AUR_PACKAGE=proxysql
  include:
    - stage: recheck package versions
      script:
      - update_versions.sh
    - stage: rebuild docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t aur-bldr .
      - docker images
      - docker tag aur-bldr $DOCKER_USERNAME/aur-bldr
      - docker push $DOCKER_USERNAME/aur-bldr
    - stage: test
      git:
        clone: false

      env:
