services:
  - docker
language: minimal
before_install:
- env | grep "AUR" > .env
script:
- docker run --rm --env-file .env gin078/aur-bldr

stages:
  - name: rebuild docker image
    env: AUR_PACKAGE=
  - test

jobs:
  include:
    - stage: rebuild docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t aur-bldr .
      - docker images
      - docker tag aur-bldr $DOCKER_USERNAME/aur-bldr
      - docker push $DOCKER_USERNAME/aur-bldr
    - stage: test
      git:
        clone: false

env:
